name: Bandit Python Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  bandit:
    runs-on: ubuntu-latest
    name: Bandit SAST Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan (HTML report)
        run: |
          bandit -r . -f html -o bandit-report.html || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-html-report
          path: bandit-report.html

