
name: OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check via Docker
        run: |
          docker run --rm \
            -v $(pwd):/src \
            --volume dependency-data:/usr/share/dependency-check/data \
            --volume $(pwd)/odc-reports:/report \
            owasp/dependency-check \
            --project "django.nv" \
            --scan /src \
            --format "ALL" \
            --out /report \
            --failOnCVSS 4

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: odc-reports
