name: Docker CI for Django.nv

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t django-nv .

      # Optional: Run container to verify it builds and starts
      - name: Run container and check health
        run: |
          docker run -d -p 8000:8000 --name django-test django-nv
          sleep 10
          docker ps

      # Log in to DockerHub using your secret credentials
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Tag and push image to DockerHub
      - name: Tag and Push to DockerHub
        run: |
          docker tag django-nv ${{ secrets.DOCKERHUB_USERNAME }}/django-nv:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-nv:latest
